'use client';

import { useState } from 'react';
import GlassCard from '@/components/GlassCard';
import RadialGauge from '@/components/RadialGauge';

const WEIGHTS = [
  { domain: 'Internet', weight: 0.15, score: 92, icon: '🌐' },
  { domain: 'Security', weight: 0.15, score: 42, icon: '🛡️' },
  { domain: 'Open Source', weight: 0.15, score: 87, icon: '🐙' },
  { domain: 'AI & ML', weight: 0.15, score: 94, icon: '🧠' },
  { domain: 'Crypto', weight: 0.10, score: 68, icon: '🪙' },
  { domain: 'Developer', weight: 0.10, score: 78, icon: '👩‍💻' },
  { domain: 'Startups', weight: 0.10, score: 71, icon: '🚀' },
  { domain: 'News', weight: 0.10, score: 65, icon: '📰' },
];

const CORRELATIONS = [
  {
    type: 'positive',
    title: 'AI Investment Drives Open Source Activity',
    description: 'High AI funding correlates with surge in open-source model releases. DeepSeek V3, Qwen, Llama releases follow major VC rounds.',
    modules: ['AI & ML', 'Open Source'],
    strength: 87,
  },
  {
    type: 'negative',
    title: 'Security Incidents vs. Market Confidence',
    description: 'Major security breaches (CrowdStrike outage, Change Healthcare) correlate with -8% crypto market dip within 72h.',
    modules: ['Security', 'Crypto'],
    strength: 64,
  },
  {
    type: 'positive',
    title: 'HN Discussion Predicts npm Adoption',
    description: 'Libraries trending on Hacker News see 340% average download increase the following week on npm.',
    modules: ['News', 'Open Source'],
    strength: 91,
  },
  {
    type: 'warning',
    title: 'Elevated Threat Level + Low Service Reliability',
    description: 'When threat level ≥ ELEVATED AND <18 services operational, expect 2-3x increase in CVE publications within 48h.',
    modules: ['Security', 'Internet'],
    strength: 72,
  },
  {
    type: 'positive',
    title: 'AI Paper Volume Drives GPU Demand',
    description: 'Days with 150+ arXiv AI submissions correlate with H100 spot price increases of 12-18%.',
    modules: ['AI & ML', 'Developer'],
    strength: 78,
  },
];

function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text);
}

export default function InsightsPage() {
  const [copied, setCopied] = useState(false);

  const healthScore = Math.round(WEIGHTS.reduce((sum, w) => sum + w.score * w.weight, 0));

  const now = new Date();
  const dailySummary = `# TechPulse Daily Summary — ${now.toLocaleDateString('en', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

## 🏥 Overall Health Score: ${healthScore}/100

## ⚡ Key Highlights

### 🌐 Internet (Score: 92/100)
- 18/20 monitored services operational
- SSL certificate issuance: ~12.4/second
- Global internet traffic: ~450 EB/day estimated

### 🛡️ Security (Score: 42/100)
- Threat Level: ELEVATED (3/5)
- Active CVEs in last 7 days: see dashboard
- Known exploited vulnerabilities: 185

### 🧠 AI & ML (Score: 94/100)
- arXiv AI papers today: 127+
- Best MMLU: GPT-4o at 88.7
- HuggingFace models trending: multiple LLMs

### 🐙 Open Source (Score: 87/100)
- GitHub trending: TypeScript and AI repos dominating
- npm downloads: ~4,977/second
- Language breakdown: JS/TS/Python leading

### 🪙 Crypto (Score: 68/100)
- BTC: ~$98K
- Fear & Greed: Greed (65)
- DeFi TVL tracking in dashboard

### 👩‍💻 Developer (Score: 78/100)
- Stack Overflow top tags: JavaScript, Python, TypeScript
- Framework wars: React still dominant
- AI coding tools rapidly gaining adoption

### 🚀 Startups (Score: 71/100)
- 1,228 unicorns globally
- AI/ML continues to dominate VC allocation at 42%

## 🔗 Cross-Domain Correlations
- AI + OSS: HIGH positive correlation (87%)
- HN + npm: STRONG predictive signal (91%)
- Security + Internet: Watch for degradation pattern

---
Generated by TechPulse | ${now.toISOString()}`;

  const handleCopy = () => {
    copyToClipboard(dailySummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="p-6 space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-cyan-400 neon-text-cyan" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
          🔗 TechPulse Insights
        </h1>
        <p className="text-slate-500 text-sm">Composite health score, cross-domain correlations, daily summary</p>
      </div>

      {/* Health Score */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <GlassCard className="flex justify-center py-6">
          <RadialGauge value={healthScore} label="TechPulse Health Score" size={180} />
        </GlassCard>
        <div className="md:col-span-2 grid grid-cols-2 md:grid-cols-4 gap-3">
          {WEIGHTS.map((w) => (
            <GlassCard key={w.domain}>
              <div className="flex items-center gap-1 mb-1">
                <span className="text-base">{w.icon}</span>
                <span className="text-xs text-slate-500 uppercase">{w.domain}</span>
              </div>
              <p className="text-xl font-bold font-mono text-cyan-400 neon-text-cyan">{w.score}</p>
              <div className="flex items-center justify-between mt-1">
                <div className="flex-1 bg-white/5 rounded h-1 mr-2">
                  <div className="h-full rounded" style={{ width: `${w.score}%`, backgroundColor: w.score >= 80 ? '#00FF88' : w.score >= 60 ? '#eab308' : '#ef4444' }} />
                </div>
                <span className="text-xs text-slate-600">{(w.weight * 100).toFixed(0)}%</span>
              </div>
            </GlassCard>
          ))}
        </div>
      </div>

      {/* Weight Breakdown */}
      <GlassCard>
        <h2 className="text-sm font-semibold text-slate-300 uppercase tracking-wider mb-4">⚖️ Score Composition</h2>
        <div className="space-y-2">
          {WEIGHTS.map((w) => (
            <div key={w.domain} className="flex items-center gap-3">
              <span className="text-base w-6">{w.icon}</span>
              <span className="text-sm text-slate-400 w-28">{w.domain}</span>
              <div className="flex-1 bg-white/5 rounded h-3 overflow-hidden">
                <div
                  className="h-full rounded transition-all duration-500"
                  style={{
                    width: `${w.score}%`,
                    backgroundColor: w.score >= 80 ? '#00FF88' : w.score >= 60 ? '#eab308' : '#ef4444',
                  }}
                />
              </div>
              <span className="text-xs font-mono text-slate-300 w-8 text-right">{w.score}</span>
              <span className="text-xs text-slate-500 w-10">×{(w.weight * 100).toFixed(0)}%</span>
              <span className="text-xs font-mono text-cyan-400 w-10 text-right">
                {(w.score * w.weight).toFixed(1)}
              </span>
            </div>
          ))}
          <div className="border-t border-white/10 pt-2 flex justify-end">
            <span className="text-sm font-bold font-mono text-cyan-400 neon-text-cyan">
              = {healthScore} / 100
            </span>
          </div>
        </div>
      </GlassCard>

      {/* Cross-Domain Correlations */}
      <GlassCard>
        <h2 className="text-sm font-semibold text-slate-300 uppercase tracking-wider mb-4">🔀 Cross-Domain Correlation Alerts</h2>
        <div className="space-y-3">
          {CORRELATIONS.map((c, i) => (
            <div key={i} className={`p-4 rounded-xl border ${
              c.type === 'positive' ? 'border-green-500/20 bg-green-500/5' :
              c.type === 'negative' ? 'border-red-500/20 bg-red-500/5' :
              'border-yellow-500/20 bg-yellow-500/5'
            }`}>
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-xs font-bold ${c.type === 'positive' ? 'text-green-400' : c.type === 'negative' ? 'text-red-400' : 'text-yellow-400'}`}>
                      {c.type === 'positive' ? '↑ POSITIVE' : c.type === 'negative' ? '↓ NEGATIVE' : '⚠ WARNING'}
                    </span>
                    <div className="flex gap-1">
                      {c.modules.map((m) => (
                        <span key={m} className="text-xs px-1.5 py-0.5 rounded bg-white/10 text-slate-300">{m}</span>
                      ))}
                    </div>
                  </div>
                  <p className="text-sm font-semibold text-slate-200">{c.title}</p>
                  <p className="text-xs text-slate-400 mt-1">{c.description}</p>
                </div>
                <div className="text-center flex-shrink-0">
                  <p className={`text-xl font-bold font-mono ${c.strength >= 85 ? 'text-green-400' : c.strength >= 70 ? 'text-yellow-400' : 'text-orange-400'}`}>
                    {c.strength}%
                  </p>
                  <p className="text-xs text-slate-600">correlation</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </GlassCard>

      {/* Daily Summary */}
      <GlassCard>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">📋 Auto-Generated Daily Summary</h2>
          <button
            onClick={handleCopy}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all border ${
              copied ? 'border-green-500/50 text-green-400 bg-green-500/10' : 'border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10'
            }`}
          >
            {copied ? '✓ Copied!' : '📋 Copy to Clipboard'}
          </button>
        </div>
        <pre className="text-xs text-slate-400 font-mono leading-relaxed bg-black/40 rounded-xl p-4 overflow-x-auto whitespace-pre-wrap max-h-96 overflow-y-auto">
          {dailySummary}
        </pre>
      </GlassCard>
    </div>
  );
}
